### ISSUE TITLE
SV calling in repeat regions?

### ISSUE THREAD

**Issue by zigge90** [PacificBiosciences/sawfish#6]
Hi,

I am wondering if it is possible to add a bed-file with repetetive regions in order to improve SV calling in these regions? Or is Sawfish performing well in repetetive regions even without specifying them?

Best wishes

**Comment by ctsa** [comment]
Thanks @zigge90 ,

Good question. We looked into how something like a tandem repeats track could be used during development, but many of the heuristics which could be applied in such regions are obviated by our haplotype assembly and alignment approach, which tends to automatically group variant signal across a TR region without being given a region track. I'm sure there are ways we could further improve accuracy with this information, so it's possible this will be recommended in a future update.

-Chris
