### ISSUE TITLE
Temporary file to store information for the reads that support the rearrangement events

### ISSUE THREAD

**Issue by JiangyanYu** [PacificBiosciences/sawfish#7]
Dear sawfish team,

Thanks for developing the tool! 

I have used sawfish to determine interesting rearrangement events that involves more than 2 genomic fragments. By manually scrolling through IGV, I noticed that these multiple events are captured actually in single reads. However, currently sawfish generates an output for the breakpoint pairs, thus these complex rearrangement is lost. Meanwhile, I would like to plot the rearrangement structure as well, but often need to manually check the breakpoints in IGV.

Therefore, I was wondering whether it is possible for sawfish to output the information for the read that supports the rearrangement event, like the fusion-transcript file in pbfusion. Or there is already a file like this, but I missed it?

Thanks a lot!

Best, Jiangyan

**Comment by ctsa** [comment]
Hi Jiangyan,

We have plans to group more types of breakpoints determined to be part of the same haplotype using the VCF `EVENT` tag. Right now this is only done for breakpoints comprising simple inversions but it shouldn't be too big of an effort to generalize it, however I don't have a timeline right now.

I do have two suggestions which could be helpful right away however:
1. We do have an optional output describing the reads supporting each SV. By adding the flag `--report-supporting-reads` to the joint-call step of sawfish you can get the supporting read output in a json format as described here:

https://github.com/PacificBiosciences/sawfish/blob/main/docs/user_guide.md#optional-variant-read-support-output

2. For visualizing multi-breakpoints events, I'd recommend checking our SVTopo visualization tool from @jbelyeu here:

https://github.com/PacificBiosciences/hifi-svtopo

...this is still under development but is already quite capable and should be able to handle many smaller-scale complex events.

-Chris

**Comment by JiangyanYu** [comment]
Dear Chris,

Thanks for your detailed information! Can't believe I missed the flag --report-supporting-reads. I will re-run my analysis to get the read information. Thanks again!

I had a quick look of SVTopo. It seems it can only draw the rearrangement structure based on the aligned ref position. Is it also possible to add another panel at the bottom to show at which position on the read itself the breakpoint is happening? 

The reason I want to have this HiFi read based structure is because I am facing breakpoints on DUX4 pseudogene regions, which are full of identical repeats. Thus the alignment on this region is basically with MAPQ of 0, leading to failed alignment to reference genome. However, the sequence on the HiFi read itself is interesting to study the gene structure after the complex rearrangements. Shall I maybe add this issue to SVTopo github?

Best, Jiangyan

**Comment by ctsa** [comment]
Thanks Jiangyan,

This sounds like an interesting problem. It might be helpful for you to connect with @xiao-chen-xc on our team who is looking into some D4Z4 analysis as well. Since this question crosses into several areas our team is working on, perhaps we could arrange a quick call to learn more about your use case and how our various development directions might be able to help. Please feel free to get in touch directly (csaunders@pacificbiosciences.com) if this sounds helpful.

-Chris

**Comment by xiao-chen-xc** [comment]
Hi Jiangyan, if you are interested in genotyping the D4Z4 repeat for FSHD, we have a HiFi WGS based tool in development. Happy to talk more about it. My email is xchen@pacificbiosciences.com.

-Xiao

**Comment by JiangyanYu** [comment]
Dear Chris and Xiao,

Thanks for the suggestions! I will get in touch with Xiao.

Best, Jiangyan

**Comment by ctsa** [comment]
Thanks, Closing this as a github issue, we can followup elsewhere.
